package agent

import (
	"strings"
	"testing"
)

func TestIsPleasantry(t *testing.T) {
	exempt := []string{
		"hi", "hello", "hey", "Hi!", "thanks", "thank you", "Thanks!",
		"ok", "okay", "k", "cool", "nice", "great", "got it",
		"sounds good", "lgtm", "ty", "np", "perfect", "cheers",
		"thanks 🙏", "ok cool", "great, thank you",
	}
	for _, m := range exempt {
		if !isPleasantry(m) {
			t.Errorf("isPleasantry(%q) = false, want true (should be exempt)", m)
		}
	}

	// Anything with a real request must NOT be exempt — the guard has
	// to engage on these.
	substantive := []string{
		"how does auth work",
		"ok so how does auth work",
		"where does the gate live",
		"thanks, now show me the parser",
		"what is in gate.go",
		"is kai gate list --json implemented",
		"yes", // "yes"/"no" mean do-it/don't, not pleasantries
		"no",
		"",
	}
	for _, m := range substantive {
		if isPleasantry(m) {
			t.Errorf("isPleasantry(%q) = true, want false (guard should engage)", m)
		}
	}
}

func TestLooksTruncated(t *testing.T) {
	truncated := []string{
		"After checking the main command code, I can…",
		"the answer is...",
		"OBSERVED:\n- foo.go:1\n\nLet me check…",
		"trailing ellipsis …  \n",
	}
	for _, s := range truncated {
		if !looksTruncated(s) {
			t.Errorf("looksTruncated(%q) = false, want true", s)
		}
	}
	complete := []string{
		"The answer is plan.json, generated by `kai ci plan`.",
		"Done. It lives in gate.go:50.",
		"Here's the list:\n- a\n- b",
		"```go\nfunc main() {}\n```",
		"", // empty handled elsewhere
		"What did you mean by that?",
	}
	for _, s := range complete {
		if looksTruncated(s) {
			t.Errorf("looksTruncated(%q) = true, want false", s)
		}
	}
}

func TestConversationSearchGuardNudge_IsActionable(t *testing.T) {
	// The nudge must tell the model what TO do (search + cite), not
	// just scold it — per the project's positive-instruction guidance.
	for _, want := range []string{"search", "kai_grep", "file:line"} {
		if !strings.Contains(conversationSearchGuardNudge, want) {
			t.Errorf("nudge missing %q:\n%s", want, conversationSearchGuardNudge)
		}
	}
}
